In [ ]:
##Q1
import numpy as np
a = np.array([7,15,6,5,9])
result1 = []
for i in a:
  result1.append(i + 2)
print('New Array: ',result1)
result2 = []
for i in a:
  result2.append(i*3)
print('New Array: ',result2)
result3 = []
for i in a:
  result3.append(i/2)
print('New Array: ',result3)



New Array:  [9, 17, 8, 7, 11]
New Array:  [21, 45, 18, 15, 27]
New Array:  [3.5, 7.5, 3.0, 2.5, 4.5]


In [ ]:
##Q2
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
def most_frequent(arr):
  values, counts = np.unique(arr, return_counts=True)
  max_count_index = np.argmax(counts)
  most_frequent_value = values[max_count_index]
  indices = np.where(arr == most_frequent_value)[0]
  return most_frequent_value, indices
most_frequent_x, indices_x = most_frequent(x)
print("Most frequent value in x: ",most_frequent_x, "has indices: ",indices_x)
most_frequent_y, indices_y = most_frequent(y)
print("Most frequent value in y: ",most_frequent_y, "has indices: ",indices_y)

[5 4 6 3 2 1]
Most frequent value in x:  1 have indices:  [0 5 7 8 9]
Most frequent value in x:  1 have indices:  [0 1 2]


In [ ]:
##Q3
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a = arr[0, 1]
b = arr[2, 0]
print("1st row, 2nd column:", a)
print("3rd row, 1st column:", b)

1st row, 2nd column: 20
3rd row, 1st column: 70


In [ ]:
##Q4
import numpy as np
Manasvi = np.linspace(10, 100, 25)
print("Array:", Manasvi)
print("Dimensions of the array:", Manasvi.ndim)
print("Shape of the array:", Manasvi.shape)
print("Total elements in the array:", Manasvi.size)
print("Data type of each element:", Manasvi.dtype)
print("Total bytes consumed by the array:", Manasvi.nbytes)
Manasvi_transposed = Manasvi.reshape(25, 1)
print("Transposed array: ", Manasvi_transposed)
print("Transposed array using T attribute: ", Manasvi.T)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total bytes consumed by the array: 200
Transposed array:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using T attribute:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
##Q5
import numpy as np
UCS420_Manasvi = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])
print("Array:\n", UCS420_Manasvi)
print("Mean:", np.mean(UCS420_Manasvi))
print("Median:", np.median(UCS420_Manasvi))
print("Maximum value:", np.max(UCS420_Manasvi))
print("Minimum value:", np.min(UCS420_Manasvi))
print("Unique elements:", np.unique(UCS420_Manasvi))
reshaped = UCS420_Manasvi.reshape(4, 3)
print("Reshaped Array: ", reshaped)
resized = np.resize(UCS420_Manasvi, (2, 3))
print("Resized Array: ", resized)

Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum value: 90
Minimum value: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:  [[10 20 30]
 [40 50 60]]
